### ISSUE TITLE
Add lakeFS connection type

### ISSUE THREAD

**Issue by itaiad200** [treeverse/airflow-provider-lakeFS#13]
Using a custom connection allows setting the fields name and better overall usability of the provider.

https://github.com/astronomer/airflow-provider-sample#adding-custom-connection-forms

https://airflow.apache.org/docs/apache-airflow/stable/howto/connection.html#custom-connection-types

**Comment by itaiad200** [comment]
Adding more information.
Today the airflow-lakefs-provider relies on an airflow connection of type HTTP, as described in the [docs](https://docs.lakefs.io/integrations/airflow.html). HTTP connections allow adding extra information through the `conn-extra` param and we use that to pass the `access_key_id` and `secret_access_key`. This works for us, but it's not as convenient as having a dedicated lakeFS connection type (by adding custom connections, as described [here](https://github.com/astronomer/airflow-provider-sample#adding-custom-connection-forms)). The custom lakeFS connection type will enable the users to fill a simple tailor-made list of params to lakeFS instead of passing a json string to be parsed by the operator.

**Comment by itaiad200** [comment]
I thought so too at first, their [manual](https://github.com/astronomer/airflow-provider-sample#adding-custom-connection-forms) says
```
To connect a form to Airflow, add the hook class name and connection type of a discoverable hook to "connection-types" in the get_provider_info method as mentioned in Defining an entrypoint
```

So I think that once the jar is loaded and the custom connection is configured properly, the new connection type should be available for usage.

**Comment by vaibhavk1992** [comment]
Got it .
So while creating and building the hook do I need to change the operator endpoint as well. As my airflow is on localhost. Just Confirming?

<img width="1346" alt="Screenshot 2023-02-25 at 12 23 02 AM" src="https://user-images.githubusercontent.com/20779598/221267121-eab8514c-3fb2-4d99-a5e3-779f1dcf59f1.png">

**Comment by itaiad200** [comment]
Hey @vaibhavk1992 , not sure I understand. The above example is for the `SampleProvider`, right? I don't see a similar `get_link` function in the lakeFS provider.

**Comment by vaibhavk1992** [comment]
Yes the above was for sample provider.
Within lakeFS it is defined in the below file under       `  "extra-links": ["lakefs_provider.operators.create_branch_operator.ExtraLink"],`.
I feel ExtraLink connect to it's local airflow. But not sure because I haven't see `ExtraLink in` the whole repo.
https://github.com/treeverse/airflow-provider-lakeFS/blob/main/lakefs_provider/__init__.py

**Comment by itaiad200** [comment]
We can start with the connection form and add custom links later.
To test the custom connection type locally you can fill the endpoint url for lakeFS to point to the local lakeFS instance, not the local airflow.

**Comment by arielshaqed** [comment]
Thanks, @vaibhavk1992 , for doing this in #49!
