### ISSUE TITLE
Verify actual workflow success in CI on Airflow

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/airflow-provider-lakeFS#27]
Currently we only verify that the commits occurred.  Verify instead that the workflow actually succeeded.  This allowed me to commit with the failure in the tests that #26 will fi.

**Comment by arielshaqed** [comment]
@vaibhavk1992 please comment on this issue (or perhaps follow it) so that I will be able to assign it to you :-)
[These lines](https://github.com/treeverse/airflow-provider-lakeFS/blob/0cd7151a800628a228eb9762bdaae607e687126a/.github/workflows/provider.yaml#L67-L75) (currently) try to verify success in the CI workflow.  But the way

**Comment by vaibhavk1992** [comment]
please tag this issue under my name. I shall keep you posted from here for queires and any updates @arielshaqed

**Comment by arielshaqed** [comment]
Thanks, @vaibhavk1992! Please lemme know if I can help (here or on Slack)...

**Comment by arielshaqed** [comment]
Fixed by @vaibhavk1992 in #48.

# THANKS!
![An Axolotl in the Salzburg(!) aquarium](https://user-images.githubusercontent.com/7802932/220548238-dec2016f-56ab-4391-b013-6f3f7e40a913.jpg)
