### ISSUE TITLE
airflow-provider-lakefs version 0.43.0 throwing error when commiting changes through lakefs-client api

### ISSUE THREAD

**Issue by judeleonard** [treeverse/airflow-provider-lakeFS#28]
I am running python version 3.7 and airflow-provider-lakefs version 0.43.0. However, when I try to commit changes via the lakefs-client I keep getting the error message 

 _def log_commits(self, repo: str, ref: str, size: int=100) -> Iterator[Any]:
TypeError: 'ABCMeta' object is not subscriptable_

**Note**
This was working just fine before I ran into this error

**Comment by arielshaqed** [comment]
This is very possibly related to Python version.

@judeleonard could you please additionally share the Airflow version that you are using?  It may be relevant.

For reference, it Works For Me &tm; on [Airflow v2.2.2](https://pypi.org/project/apache-airflow/2.2.2/) on AWS MWAA.  (And to be clear, minor typing issues should not be a reason to require a particular Airflow version...)

**Comment by judeleonard** [comment]
> This is very possibly related to Python version.
> 
> @judeleonard could you please additionally share the Airflow version that you are using? It may be relevant.
> 
> For reference, it Works For Me &tm; on latest Airflow (2.3.2) during the tests. It manages to fail even on [Airflow v2.2.2](https://pypi.org/project/apache-airflow/2.2.2/) on AWS MWAA. (And to be clear, minor typing issues should not be a reason to require a particular Airflow version...)


I'm running on  Airflow verison 2.2.4
