### ISSUE TITLE
Backwards compatibility to version 2.4.3

### ISSUE THREAD

**Issue by FredrikBakken** [treeverse/airflow-provider-lakeFS#71]
# Goal

Use `airflow-provider-lakeFS` with Managed Airflow in Azure. Latest supported version of Airflow by Azure in Azure Data Factory is `v2.4.3`.

# Problem Description

Latest version of `airflow-provider-lakeFS` passes `TaskInstance.note` along with the metadata, making it only work with Apache Airflow v2.5.0 and later.

**Comment by arielshaqed** [comment]
Note to self:
* [ ] First pull #72 -- fixes the problem.
* [ ] But then figure out a way to do it _without_ examining versions.  The code is brittle; prefer to examine _whether_ we have a note on `TaskInstance` and then include it.

**Comment by FredrikBakken** [comment]
I agree with your suggestion to avoid version checking as a best practice. This also gave me an idea for something to try tomorrow that might solve that 🙌

**Comment by arielshaqed** [comment]
Thanks!  But to be clear: I'd rather get you unstuck *today* and refactor
*later*: at worst we fix it the next time we need a property that has no
backwards compatibility.
